---
title: "Cases by Time"
output: 
  html_document: 
    toc: yes
    toc_float: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggridges)
library(patchwork)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

## date cleaning

```{r cars}
source("data_preprocessing_backbone.R")
logistic_cases = age %>%
    select(total_cases, date) %>%
    group_by(date) %>%
    summarize(total_cases=sum(total_cases)) %>%
    arrange(date) %>%
    mutate(day = 1:length(date)) %>%
    dplyr::select(-date) %>%
    relocate(total_cases)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
reg_logit = glm(total_cases~day,data = logistic_cases)
summary(reg_logit)

plot(reg_logit)
```


