---
title: "Project Report"
output: 
  html_document: 
    toc: yes
    toc_float: yes
editor_options: 
  chunk_output_type: console
---
## P8105：Final Project Report
#### Runze Cui (rc3521), Zhengwei Song (zs2539), Shangsi Lin (sl5232), Yunxi Yang (yy3297), Jiahe Deng (jd3924)
### Introduction
#### Motivation
With the spread of COVID-19 enters its third year, the human society seem to have accepted its existence and accepted it as part of our daily lives. However, that doesn't mean COVID has stopped its harm on the public. with the huge amount of studies on COVID-19 in multiple different disciplines of studies, researchers and scholars have understand its influence more than ever, and agreed on the fact that COVID has disproportionately harmed certain groups of people more than others due to [race, economic, or social status.](https://www.tandfonline.com/doi/full/10.1080/01419870.2020.1851382)

With interest in investigating more on factors that can influence people's chances of getting the disease, the builders of this website decided to look specifically into one state of America: California. California is chosen due to its large geographic area, relatively large population size, and relatively modern infrastructures. It is likely that California's picture during the pandemic can be interpreted as a reference to other regions with high population across the world. Since COVID-19 is a highly transmissible disease to start with, this is ideal knowledge that analysts want to gain insight on.

#### Related Work
As stated in motivation, there are many published works focused on COVID since its first outbreak. To gain as much insight on the Initial questions as possible, the analysts mainly looked at literature related to COVID spreading in the region of California. 

[A particular paper](https://www.healthaffairs.org/doi/full/10.1377/hlthaff.2020.00598) was very valuable to this investigation as it analyzed more than a thousand cases of COVID-19 patients in California during a time period that overlaps partly with our time period of investigation interest.It used multivariable logistic regression to assess the risk of hospitalization for the patients, which is also a regression method that this investigation intend to use. Thus, it was a very good reference literature.

Since part of the data set that this study is based on are focused on different age groups and their chance of hospitalization and infection of COVID-19. One of the key factors that analysts are interested in is age.
To understand this particular sector better, [this piece of literature](https://www.science.org/doi/full/10.1126/science.abe8372) provided lots of information on the "source age group" of resurgence of cases during the pandemic, and offered insights on potential confonders that needs to be mentioned and discussed in this investigation. 

Apart from populations that gets the disease, it is also necessary to discuss the most popular measure for public to avoid getting the disease in the first place: vaccination. There are lots of published papers, articles, and [websites](https://www.gavi.org/covid19-vaccines?gclid=Cj0KCQiAkMGcBhCSARIsAIW6d0BUi9lbMMWwoJ7FTmCexEJBhB4GvVsFFIvKkecWwx0-56lMKlHI0wUaApzqEALw_wcB) informing public the effect and basic knowledge about the vaccine. However, there are still groups of people who doesn't take the vaccine due to many different reasons such as religion, personal beliefs, economic difficulties or hardship of getting access to the vaccine. 

Through analyzing extracted dataset, it is the hope of this investigation to find certain populations that are least likely to take the vaccine and propose potential future works to find out what caused the observed pattern. To better understand the process, analysts looked at [a paper published on CDC official website](https://www.cdc.gov/mmwr/volumes/71/wr/mm7104e1.htm?fbclid=IwAR0V9HbHoK8TZNZd5PptJoahzzS2qpwVCGAztIvAZzNNdPLweSaPWCYPnGU) to gain valuable insights.It is mentioned in this work that the least vaccined group keeps changing as time pass by. suggesting that timeliness is something that should be considered in later discussion.

[The COVID website](https://covid19.ca.gov/) created by the government of California is also a big inspiration in the creation process of this website, as builders designed part of the planning of this website while referring to it.

#### Initial questions
Our initial questions is how does different factors(e.g. Race, Age, Demographic factor, gender) influence on the hospitalization and disease odds for an individual or social group in the state of California. Particularly, does different sex groups have difference in their vaccination rate? In what parts of California tend to have the highest prevalence of the disease? How does the hospitalization rate differs among each racial group? Are teenagers being considered as a vulnerable group towards the virus, judging based on the data set we have? 

### Data 

#### CHHS
A major part of the data used in this investigation originally came from [California Health and Human Service Open Data Portal](https://data.chhs.ca.gov/organization/california-department-of-public-health). This is a website with numerous databases, directly held by the agency of California health and human services, abbreviated as CHHS. California health and human service is the state agency tasked with administration and oversight of "state and federal programs for health care, social services, public assistance and rehabilitation" in the U.S. state of California. The agency is headed by the Secretary of the California Health and Human Services Agency, with headquarters in Sacramento. Many of the laws in the California Health and Safety Codes are enforced by it. 

This data portal includes data related to public health activities across the state of California. Most of which is collected at the county level but there are also data sets that contains data at individual level.

The three specific datasets that will be used for this investigation later is listed below, extracted from the site by simply downloading them into the R project:

[First data set](https://data.chhs.ca.gov/dataset/covid-19-time-series-metrics-by-county-and-state) : This data set focuses at information such as demographic category, total cases, case percentage, death, and report date related to COVID-19 in different counties of the state of California.

[Second data set](https://data.chhs.ca.gov/dataset/covid-19-post-vaccination-infection-data) : This data set focuses on the COVID-19 disease information on vaccination status, including variables such as vaccinated cases vs. unvaccinated cases, vaccinated death vs. unvaccinated death.

[Third data set](https://data.chhs.ca.gov/dataset/covid-19-hospital-data): This data set is focused on the hospitalization by county in California. Besides recording the amount of people that are hospitalized, it offers comparison between the hospitalized COVID confirmed patients, and ICU suspected covid patients in the region. 

#### Opendatasoft

In order to present an interactive map to users that contains population infected by time in different counties, analysts referred to geographic coordination data online for each county. 

Opendatasoft is a French company that offers data sharing software. Based in Paris, it also has a subsidiary in Boston (United States) and an office in Nantes(France).
Opendatasoft has developed a tool for sharing and reusing the data of companies and public administrations. Its software lets people organize, share, and visualize any type of data. The software can be used by both private companies and public entities. The [geographic data set](https://public.opendatasoft.com/explore/dataset/us-county-boundaries/table/?disjunctive.statefp&disjunctive.countyfp&disjunctive.name&disjunctive.namelsad&disjunctive.stusab&disjunctive.state_name&sort=stusab&refine.stusab=CA) this investigation is interested in from Opendatasoft is information about US County Boundaries.  

#### USA.com
This is a website contains data about states, metro areas, counties, cities, zip codes, and area codes information, including population, races, income, housing, etc. In this investigation, data extracted from this website is about county areas in California through [this link](http://www.usa.com/rank/california-state--land-area--county-rank.htm).

#### Employment Development Department
Since 1935, the Employment Development Department(EDD) had been connecting with job seekers and employers in an effort to build the economy of Golden State. Mean while it has been collecting data related to employment each month by industry data for California and sub-state areas. One of its data set is [current industry employment and unemployment rates for counties](https://www.labormarketinfo.edd.ca.gov/data/industry-employment-and-unemployment-rates-for-counties.html), which could produce insightful result through this investigation by connecting data like unemployment rate to the prevalence of disease or hospitalization rate. 
A
The data cleaning process is being presented in the index page, you can go to there by clicking on the button at the upper left corner.

### Inference Analysis: Regression
#### Multiple linear Regression 

For model building purpose of this investigation, a multiple linear regression model is considered to investigate on hospitalization rate. The underlying logic for this model is relatively simple, analysts extract data that includes disease prevalence, area, population, location and tests. The hypothetical multiple linear regression function for this particular inference analysis is shown as below:

disease prevalence = B0 + B1 * tests + B2 * unemployment + B3 * area + B4 * population + B5 * location

In the above equation, disease prevalence is the desired outcome while the amount of tests, unemployment, area, location, and population are predictors. B1, B2, B3, B4 and B5 are the factors for each predictors respectively. Under ideal circumstances, we would expect our model to be able to predict the death counts in a region, given its number of tests, population, and unemployment rate. 

It is necessary to mention that in the original dataset on which this model looked at, analysts observed strong correlation within the some other data variables such as `vaccination` and `labor_rate`. After some data exploratory works, some right-skewness is noticed so analysts decided to apply natural logarithms to each continuous variables.

Another thing to look at was the correlation between the predictors to avoid the potential effect of multicollinearity, which is a statistical concept that describes the incidence of  several independent variables in a model are in fact correlated within themselves. This correlation test is later combined with criterion based model selection to select which predictors to put in for the final model.

The three criterion based model selection method are Cp criterion, adjusted R squared criterion, and LASSO. The results of these model selection method all gave similar predictor size, so in the end the analysts chose four predictors to construct the final model as shown in the equation above. After the construction of this model, a corss validation process is performed to further assess the prediction ability of this model.

### Discussion
#### Project Obstacle

One of the first obstacles this project met was related with data scraping and cleaning. It was the groups' intention to perform similar investigations about COVID, but on a much more broader scale such as across the whole country. The reason that analysts didn't follow this starting plan is because data sets from different parts of the country simply are organized quite differently. So it would take analysts a lot of time to do the necessary bindings to forge a complete data set to work on. Also it is questioned whether the equipment that analysts use can efficiently process such large amount of data in reasonable time during later analysis process.

After deciding to put our focus on the state of California, the next obstacle analysts met was related to data pre-processing. There were lots of data variables retrieved from the original database that aren't going to be used in this investigation and also certain variable columns need to be created using the `mutate` function. As team members excahnged a lot of ideas when discussing and planning on which specific data to throw out and which ones to keep, sometimes there were even data manipulations going "back and forth", the website building process didn't really start for quite a long time. 

Formulating the right regression model and choosing the right variables to draw graphs were challenges as well. Due to lots of multicolinearity in our original data set, analysts had to run multiple model selection to decide which variables to include in the final model. A larger issue was that some originally designed plotting turned out to be just not feasible due to errors from the data set, for example in some cases, the death rate of a county was 100%, which is clearly wrong. It was also a challenge overall to interpret correlations after the  model is built and summarization of the model given using code because most of the correlations aren't perfect, there could be confounders that we haven't considered in the model. 

#### Findings
